spring:
  application:
    forward-headers-strategy: framework
  security:
    qrcheck:
      api-key:
        token:
          outgoing: ${API_KEY_OUTGOING}
      oauth2:
        auth-server:
          host: ${AUTH_HANDLER_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: qrcodes
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/qrcheck
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/qrcheck
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: qrcodes
  liquibase:
    enabled: false
  groovy:
    template:
      check-template-location: false
  sleuth:
    jdbc:
      p6spy:
        enabled: true
        enable-logging: true
        log-format: '%(sql) {executed in %(executionTime) msec}'
        custom-appender-class: ru.softdarom.qrcheck.qrcode.handler.util.logger.P6SpyLogger
        logging: slf4j
        tracing:
          include-parameter-values: true

springdoc:
  api-docs:
    path: /swagger-api
  swagger-ui:
    path: /
  info:
    title: QRCode RESTful API
    description: Сервис для работы с qrcode
    version: V1
    licence-url: https://qrchk.ru/licence
    owner-name: QRCheck
    owner-url: https://qrchk.ru
    owner-email: it.support@softdarom.ru

logbook:
  strategy: body-only-if-status-at-least
  format:
    style: http
  logger:
    name: REST
  exclude:
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-api/**